### ISSUE TITLE
Album properties failing since v1 with immich v3

### ISSUE THREAD

**Issue by rafaelsavi** [Salvoxia/immich-folder-album-creator#298]
After updating immich to v3.0.0 and immich-folder-album-creator to v1.0.0, I get a AttributeError: 'str' object has no attribute 'value'.
It happens in the logging.debug of immich_auto_album.py L745

The issue only happens since the update and only if UPDATE_ALBUM_PROPS_MODE>0 or if starting album from scratch using READ_ALBUM_PROPERTIES

**Comment by Salvoxia** [comment]
Most likely related to how your `.albumprops` file is set up. Can you please share the contents of the `.albumprops` file causing the issue when trying to create the album from scratch so that I can try to reproduce the issue?

**Comment by rafaelsavi** [comment]
Here's the content of the `.albumprops`, with hidden emails:

```
inherit: true
share_with:
  - user: "x.xx@gmail.com"
    role: "viewer"
  - user: "xx@gmail.com"
    role: "viewer"
  - user: "x@gmail.com"
    role: "viewer"
  - user: "xx.xx@gmail.com"
    role: "viewer"
  - user: "x.x@gmail.com"
    role: "viewer"
```

Error details:
```
time="2026-07-05T21:38:55+02:00" level=info msg="Adding assets to album Família XX | XXX"
Traceback (most recent call last):
  File "/script/immich_auto_album.py", line 2392, in <module>
    folder_album_creator.run()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/script/immich_auto_album.py", line 2192, in run
    self.api_client.update_album_shared_state(album, True, users)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  File "/script/immich_auto_album.py", line 745, in update_album_shared_state
    logging.debug("Album %s shared with users IDs %s in role: %s", album_to_share.get_final_name(), share_users, share_role_group.value)
                                                                                                                
AttributeError: 'str' object has no attribute 'value'
```

Folder path: `XX\1999\10 - XXX`

Env Settings:
```yaml
  UNATTENDED: 1
  READ_ALBUM_PROPERTIES: 1
  UPDATE_ALBUM_PROPS_MODE: 2
  IGNORE: "**/@Recycle/**:**/RAW/**"
  FIND_ASSETS_IN_ALBUMS: 1 
  CHUNK_SIZE: 1000
  FETCH_CHUNK_SIZE: 2500
  TZ: Europe/Berlin
  ALBUM_SEPARATOR: " | "
  ALBUM_NAME_POST_REGEX1: "'(^|\\s\\|\\s)\\d{2}\\s-\\s' '\\1'"
  ALBUM_NAME_POST_REGEX2: "'[ _-]+$$' ''"
  ALBUM_NAME_POST_REGEX3: "'^(.*?)\\s\\|\\s\\d+\\s\\|\\s(.*)$$' '\\1 | \\2'"
  ALBUM_NAME_POST_REGEX4: "'(?:\\s\\|\\s){2,}' ' | '"
  ALBUM_NAME_POST_REGEX5: "'^\\s\\|\\s|\\s\\|\\s$$' ''"
```

**Comment by rafaelsavi** [comment]
I see that it works without issues if I remove `role: "viewer"` entries form the albumprops and leave just the users

**Comment by Salvoxia** [comment]
Thanks for that hint, I think I now where things go wrong now.

**Comment by Salvoxia** [comment]
Should be fixed in the `edge` tag if you're inclined to test it.

**Comment by rafaelsavi** [comment]
it's tested and working, thank you lots

**Comment by Salvoxia** [comment]
Thank you for your feedback!
